---
- name: Enabling extra Repositories
  dnf:
    name: "{{ pkg }}"
    state: latest

# - name: Update the system.
#   dnf:
#     name: "*"
#     state: latest

- name: Update the system.
  command: dnf distro-sync -y
#   when_"{{ pkg }}"" state == latest