---
- name: Enabling extra Repositories
  dnf:
    name: "{{ pkg }}"
    state: latest

# - name: Update the system.
#   dnf:
#     name: "*"
#     state: latest

- name: Update the system.
  command: dnf distro-sync -y
  register: command
  changed_when: "'No Packages marked for Distribution Synchronization' not in command.stdout"
